version: '3.4'

services:

  rabbitmq:
    image: rabbitmq:3
    
  servicea:
    image: ${DOCKER_REGISTRY-}servicea
    build:
      context: .
      dockerfile: ServiceA/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - rabbitmq
